# Generated by Django 3.1.7 on 2021-05-27 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tipo', models.IntegerField()),
                ('peso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pajilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganaderia.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateTimeField()),
                ('tipo', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganaderia.cliente')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganaderia.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField()),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganaderia.animal')),
                ('id_veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganaderia.veterinario')),
            ],
        ),
        migrations.CreateModel(
            name='VacaMadre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Embarazada', models.IntegerField()),
                ('fecha_inseminacion', models.DateTimeField()),
                ('litros', models.IntegerField(blank=True, null=True)),
                ('id_veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganaderia.veterinario')),
                ('pajilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganaderia.pajilla')),
            ],
        ),
        migrations.CreateModel(
            name='Ternero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.IntegerField()),
                ('destete', models.DateTimeField()),
                ('remplazo', models.IntegerField()),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganaderia.animal')),
                ('madre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Madre', to='ganaderia.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('fecha_parto', models.DateTimeField()),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganaderia.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedadades',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('final', models.DateTimeField(blank=True, null=True)),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganaderia.animal')),
                ('id_veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganaderia.veterinario')),
            ],
        ),
        migrations.CreateModel(
            name='Baja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganaderia.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('kilos', models.IntegerField()),
                ('consumo_agua', models.IntegerField()),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganaderia.animal')),
            ],
        ),
    ]
