# Generated by Django 3.1.7 on 2021-06-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0004_auto_20210601_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermedadades',
            name='inicio',
            field=models.DateTimeField(),
        ),
    ]
