# Generated by Django 3.1.7 on 2021-06-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0005_auto_20210601_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baja',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='enfermedadades',
            name='final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enfermedadades',
            name='inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evolucion',
            name='mes',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pajilla',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ternero',
            name='destete',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vacamadre',
            name='fecha_inseminacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(),
        ),
    ]
