# Generated by Django 3.1.7 on 2021-06-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0006_auto_20210601_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentacion',
            name='fecha',
            field=models.DateField(),
        ),
    ]
